Vagrant.configure("2") do |config|

    config.vm.box = "bento/ubuntu-18.04"
  
    config.vm.network "private_network", ip: "192.168.56.30"
  
    config.vm.provider :virtualbox do |v|
  
        v.customize ["modifyvm", :id, "--memory", 2048]
  
    end
  
end